sudo: required
language: python
python:
  - "3.4"
before_install: sudo apt-get install telnet
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
 - sim/telserver.py linux &
 - nosetests src/pyco/test/unit/test_linux.py
